spring:
  application:
    name: t1-academy

  #Datasource configuration
  datasource:
    url: jdbc:postgresql://localhost/t1-academy
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  #JPA
  jpa:
    hibernate:
      ddl-auto: validate
