INSERT INTO task (id, title, description, user_id) VALUES
                                                       (nextval('task_seq'), 'NOT STARTED', 'Первая задача', 1),
                                                       (nextval('task_seq'), 'IN PROGRESS', 'Вторая задача', 1),
                                                       (nextval('task_seq'), 'DONE', 'Третья задача', 2),
                                                       (nextval('task_seq'), 'NOT STARTED', 'Четвертая задача', 2),
                                                       (nextval('task_seq'), 'IN PROGRESS', 'Пятая задача', 3),
                                                       (nextval('task_seq'), 'DONE', 'Шестая задача', 3),
                                                       (nextval('task_seq'), 'NOT STARTED', 'Седьмая задача', 4),
                                                       (nextval('task_seq'), 'IN PROGRESS', 'Восьмая задача', 4),
                                                       (nextval('task_seq'), 'DONE', 'Девятая задача', 5),
                                                       (nextval('task_seq'), 'NOT STARTED', 'Десятая задача', 5),
                                                       (nextval('task_seq'), 'IN PROGRESS', 'Одиннадцатая задача', 6),
                                                       (nextval('task_seq'), 'DONE', 'Двенадцатая задача', 6),
                                                       (nextval('task_seq'), 'NOT STARTED', 'Тринадцатая задача', 7),
                                                       (nextval('task_seq'), 'IN PROGRESS', 'Четырнадцатая задача', 7),
                                                       (nextval('task_seq'), 'DONE', 'Пятнадцатая задача', 8);